# Table positions in the map frame (measure from RViz using "Publish Point")
# yaw is in radians (0 = facing +X, 1.57 = facing +Y, 3.14 = facing -X)

home:
  x: -0.0733
  y: -2.65
  yaw: 0.047

tables:
  table-1:
    x: 2.780
    y: 0.060
    yaw: 1.5708
  table-2:
    x: 3.096
    y: -3.744
    yaw: 0.039
